export const individualFormStep = [
  'ACCOUNT DETAILS',
  'PERSONAL DETAILS',
  'MONTHLY INCOME DETAILS',
  'ASSETS',
  'LIABILITIES',
  'GENERAL LIVING EXPENSES PER MONTH',
  'BACKGROUND TO HARDSHIP',
  'BACKGROUND TO HARDSHIP continued',
  'PROPOSAL FOR ASSISTANCE',
  'DECLARATION',
];
